### ISSUE TITLE
Bigger simulation frame?

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/eduwrench#22]
I know this is tricky to fix but it's a bit inconvenient to have to scroll in the simulation frame: maybe it could be made higher or just resizable?

**Comment by rafaelfsilva** [comment]
The iframe is being removed. Here it is the current status of implementation:
- [x] remove iframe from all modules
- [x] Gantt and host utilization charts should have additional param for containerId
- [x] form fields for simulation should have unique ID across tabs in a module
- [ ] figure `span` should be unique
- [ ] task data table should have unique id per module tab
