### ISSUE TITLE
PDC::MulticoreComputing::Parallelism: Too many questions

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/eduwrench#27]
Yes, but I find them a bit too numerous in "Parallelism". Maybe split them in two sections: basic and advanced?

**Comment by henricasanova** [comment]
I removed one of the practice questions.But overall, I am not sure I agree with the comment that there are too many questions. We have 3 sections, with 2, 4, and 2 practice questions, and 6 non-practice questions at the end. 

One option would be to split the "Parallelism tab" into two: 
  - Parallelism: Speedup and Efficiency
  - Load Balancing: the 2nd half of the Parallelism tab

I am suggesting this as it is  true that this tab is really a 2-part thing. First we define the metrics, then  we say "now you're wondering why speedup isn't always perfect!! Keep reading". The "Keep reading" could be: go to the next tab!

I sort of like this idea. @rafaelfsilva What do you think?

**Comment by rafaelfsilva** [comment]
I agree with you. The hard thing is to find the right balance between the number of tabs and the length of the tabs content, but I think in this case it makes sense breaking them into two tabs
