### ISSUE TITLE
New page: for teachers and instructors

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/eduwrench#43]
Explain who the material is for, how to integrate it into courses, who to contact for help/suggestions, etc.    Deploy on their own servers.

**Comment by henricasanova** [comment]
@rafaelfsilva  I drafted a "for students" and a "for teachers" page. Can you review /edit the content (it's in branch called "for_instructor_page". (I opted to add a "for students" page after all)

**Comment by rafaelfsilva** [comment]
I have done some minor edits to both pages. I think it is ready for deployment.

**Comment by henricasanova** [comment]
merged and closing this issue.
