### ISSUE TITLE
Glossary not closable on front page

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/eduwrench#5]
The Glossary, when opened on the front page, doesn't show its little tab and thus cannot be closed (only reloading the page will work). This isn't the case on the Modules page, which  is great, and makes me think it's easy to fix?   Observed with Firefox, Google,  Safari and  Chrome on MacOS

**Comment by vivianzzhu91** [comment]
Fixed! Took a long time to figure out: it's a mismatched closing div tag issue.  See [this](url) commit with further detail.
