### ISSUE TITLE
SimGrid linking on Mac

### ISSUE THREAD

**Issue by jwfeuerstein** [wrench-project/eduwrench#52]
There is an issue with linking to SimGrid when building simulators on MacOS. In the CMakeLists.txt file for each simulator, `set(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} /opt/simgrid/lib)` should be added. Also, `/opt/simgrid/include` should be added to the list of directories in the `include_directories` statement.

**Comment by henricasanova** [comment]
How did you install SimGrid. By Default, SimGrid is installed in /usr/local/ 
I just double-checked with SimGrid  3.26, and after just doing a Cmake, it says that the install prefix is /usr/local/   I can't figure out how you got it in /opt.  Unless you installed it with a special prefix?  Or are you putting the simgrid source in /opt and not doing a "make install"? Let's chat on Slack...

**Comment by rafaelfsilva** [comment]
@henricasanova on Jason's installation, SimGrid ended up in `/opt/simgrid` after doing `sudo make install`

**Comment by henricasanova** [comment]
@jwfeuerstein  @rafaelfsilva  This is unreal. I would need to see the last "page" of output after the successful "cmake -Denable_smpi=off ."  That is, after the  "End of configuration headers" marker with all the # signs.

**Comment by henricasanova** [comment]
This was resolved by removing all generated cmake files and reconfiguring.
