### ISSUE TITLE
labels in svg pictures  not updated dynamically

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/eduwrench#6]
It  used to be that, when running  a simulator, changing values  in input textfields would update the  labels in the  svg images. I  just noticed that this no longer worked when  I tried to implement  a  new simulator, and then  went back to the IO simulator to double-check.  It  seems that the  code in web/public/sims/scripts/io_operations.js that does at, for instance, 

> // Update the label that says how much GFlop each task is. 
> // Converts to TFlop to save space if it gets too large.
>     $("#task-gflop").on("keyup", function () {
>         let task_gflop_input_el = $(this);
>         ...

is executed on the  keyup event, as it should, but then doesn't update  the label in the  svg. I have no idea why. This is obviously not a showstopper, and we can keep adding content and simulators for a while, but eventually  we likely need to fix this as it makes the user  experience much better

**Comment by vivianzzhu91** [comment]
Fixed by changing include svg with dynamic contents instead of img tag. Convert .ejs files to jekyll static format sometimes can be incompatible.

**Comment by rafaelfsilva** [comment]
I have just tested it and it worked well. I am closing this issue. Thanks!
