### ISSUE TITLE
Figure width

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/eduwrench#7]
really not sure how to handle figure widths. They seem to bleed out of the margins, and increasing/decreasing font sizes leads to odd behaviors...

**Comment by rafaelfsilva** [comment]
@henricasanova, I have committed an attempt to fix the figure width issues. Let me know if it works better now.

**Comment by henricasanova** [comment]
I don't think it makes much of a difference. When resizing the window the figure doesn't shrink but just spills over the margins. Things do seem less weird when changing the browser font size though!

**Comment by rafaelfsilva** [comment]
yeah, I made it work with the font resize, so figures resize accordingly. I will keep looking to into the window resizing.
