### ISSUE TITLE
Fix the "sign in" so that one cannot run a simulation if not signed in

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/eduwrench#82]

**Comment by rafaelfsilva** [comment]
This is related to a cookie issue. For instance, if the server gets restarted, previous cookies are not valid anymore, however the browser still keeps old cookies and assume they are still valid.

**Comment by rafaelfsilva** [comment]
@henricasanova, I have pushed an attempt to fix the login issue. Please, let me know if you still see strange behaviors.

**Comment by henricasanova** [comment]
issue has been resolved!
