### ISSUE TITLE
Dashboard: tooltips on left of screen 

### ISSUE THREAD

**Issue by rafaelfsilva** [wrench-project/eduwrench#9]
From Henri: `The tooltips that show up when hovering over graphs show up on the left-hand side of the window instead of where the mouse is.`

**Comment by henricasanova** [comment]
The tooltips are no longer on the left-side of the screen, which is great. But now there's to far down or too narrow. This is a tiny detail. To see what I mean, open the simulator on the first tab of the Multicore module, and run the simulation for 3 cores and 10 tasks.  Then hover over the task rectangles in the display. You'll see that when you hover over the task rectangles toward the end of the execution, the tooltips are narrowed and  their bottom line is thus invisible.   

On a side note, I wonder if it wouldn't be useful for the tooltips to indicate start date and end date as well (unless they already do and that content is invisible as well?)

**Comment by rafaelfsilva** [comment]
That's weird. This is how I see it in Chrome and Safari:

<img width="1068" alt="Screen Shot 2020-06-09 at 11 33 07 AM" src="https://user-images.githubusercontent.com/4711875/84186284-2e089080-aa45-11ea-99a0-d8ad75543067.png">

Are you using zoomed window?

**Comment by henricasanova** [comment]
I am talking about the host utilization graph, not the task view.

**Comment by rafaelfsilva** [comment]
I see. I think some recent changes broken it.

This is how it looks like on the one that is deployed at (eduwrench.org):
<img width="1068" alt="Screen Shot 2020-06-09 at 12 02 58 PM" src="https://user-images.githubusercontent.com/4711875/84189018-6316e200-aa49-11ea-9c56-e4b1e8ca8251.png">

and here it is the one I just started in my computer:
<img width="1068" alt="Screen Shot 2020-06-09 at 12 03 21 PM" src="https://user-images.githubusercontent.com/4711875/84189045-7164fe00-aa49-11ea-9669-74d65e9c0a4d.png">

I am going to investigate it now.

**Comment by henricasanova** [comment]
yep. the one deployed looks great... sorry to always be the one raising annoying issues   (you should talk to the SimGrid guys about that ;)).   I tried again, and sometimes the tooltips (in the host utilization graph) are stuck on the left....

**Comment by rafaelfsilva** [comment]
no worries!! :)
It is better you raising the issues than a user being frustrated with the system. I will be committing the fix soon.

**Comment by rafaelfsilva** [comment]
@henricasanova That was an issue with a function on the dashboard code. If you redeploy wrench it should work now.

**Comment by henricasanova** [comment]
Awesome! thanks! Closing the issue.
